<?php

namespace GitlabBundle\Repository;

use GitlabBundle\Entity\CommentImportLog;

/**
 * CommentImportLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentImportLogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastImportedId()
    {
        /** @var CommentImportLog $lastImport */
        $lastImport = $this->findOneBy([], ['date' => 'DESC']);

        if ($lastImport) {
            return $lastImport->getLastImportNote();
        }

        return 0;
    }
}
