<?php

namespace GitlabBundle\Repository;

use GitlabBundle\Entity\MergeRequestImportLog;

/**
 * MergeRequestImportLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MergeRequestImportLogRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return int
     */
    public function findLastImportedId()
    {
        /** @var MergeRequestImportLog $lastImport */
        $lastImport = $this->findOneBy([], ['date' => 'DESC']);

        if ($lastImport) {
            return $lastImport->getLastImportMergeRequest();
        }

        return 0;
    }

    /**
     * @param int $id
     */
    public function setLastImportedId($id)
    {
        $importLog = new MergeRequestImportLog((int) $id);

        $this->getEntityManager()->persist($importLog);
        $this->getEntityManager()->flush($importLog);
    }
}
