<?php

namespace GamificationBundle\Repository;

use GamificationBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $name
     */
    public function ensureExists($name)
    {
        /** @var User $user */
        $user = $this->findOneBy(['name' => $user]);

        if (!$user) {
            $user = new User($name);
            $this->add($user);
        }
    }

    /**
     * @param User $user
     */
    public function add(User $user)
    {
        $this->getEntityManager()->persist($user);
        $this->getEntityManager()->flush($user);
    }
}
