gamification:
    resource: "@GamificationBundle/Controller/"
    type:     annotation
    prefix:   /

gitlab:
    resource: "@GitlabBundle/Controller/"
    type:     annotation
    prefix:   /

event:
    resource: "@EventBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
