gitlab:
    resource: "@GitlabBundle/Controller/"
    type:     annotation
    prefix:   /

badge:
    resource: "@BadgeBundle/Controller/"
    type:     annotation
    prefix:   /

event:
    resource: "@EventBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
