<?php

namespace EventBundle\Repository;

use EventBundle\Entity\Counter;
use EventBundle\Entity\RepositoryEvent;

/**
 * CounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CounterRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCounter(RepositoryEvent $event)
    {
        $counter = $this->findOneBy(['name' => $event->getEvent(), 'user' => $event->getUser()]);

        if (!$counter) {
            $counter = new Counter($event->getEvent(), $event->getUser());
        }

        return $counter;
    }

    public function getCounterFor($user)
    {
        return $this->findBy(['user' => $user]);
    }

    public function save(Counter $counter)
    {
        $this->getEntityManager()->persist($counter);
        $this->getEntityManager()->flush($counter);
    }
}
