<?php

namespace EventBundle\Repository;

/**
 * RepositoryEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryEventRepository extends \Doctrine\ORM\EntityRepository
{
}
