<?php

namespace EventBundle\Repository;

use EventBundle\Entity\RepositoryEvent;

/**
 * RepositoryEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryEventRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param RepositoryEvent $event
     */
    public function add(RepositoryEvent $event)
    {
        $this->getEntityManager()->persist($event);
        $this->getEntityManager()->flush($event);
    }

    /**
     * @param RepositoryEvent $event
     * @return bool
     */
    public function exists(RepositoryEvent $event)
    {
        return $this->findOneBy([
            'event' => $event->getEvent(),
            'user' => $event->getUser(),
            'repositoryReference' => $event->getRepositoryReference(),
        ]) !== null;
    }

    public function findByUser($user)
    {
        return $this->findBy(['user' => $user]);
    }
}
