services:

  event_bundle.doctrine.orm.repository_event_repository:
    class: EventBundle\Repository\RepositoryEventRepository
    factory: [ "@doctrine.orm.entity_manager", 'getRepository' ]
    arguments:
      - EventBundle\Entity\RepositoryEvent
